version = 1

test_patterns = [
  "tests/**",
  "test_*.py"
]

exclude_patterns = [
  "migrations/**",
  "**/examples/**"
]

[[analyzers]]
name = "javascript"
enabled = true

  [analyzers.meta]
  plugins = ["react"]
  environment = ["mongo", "jquery"]
  module_system = "es-modules"
  dialect = "flow"
  skip_doc_coverage = ["class-expression", "method-definition"]

[[analyzers]]
name = "python"
enabled = true
dependency_file_paths = ["requirements/development.txt"]

  [analyzers.meta]
  runtime_version = "3.x.x"
  type_checker = "mypy"
  max_line_length = 88
  skip_doc_coverage = ["module", "magic", "init"]
  additional_builtins = ["_", "pretty_output"]

[[analyzers]]
name = "ansible"
enabled = true

[[analyzers]]
name = "csharp"
enabled = true

[[analyzers]]
name = "cpp"
enabled = true

[[analyzers]]
name = "docker"
enabled = true

[[analyzers]]
name = "java"
enabled = true

[[analyzers]]
name = "php"
enabled = true

[[analyzers]]
name = "ruby"
enabled = true

[[analyzers]]
name = "rust"
enabled = true

[[analyzers]]
name = "scala"
enabled = true

[[analyzers]]
name = "shell"
enabled = true

[[analyzers]]
name = "sql"
enabled = true

[[analyzers]]
name = "terraform"
enabled = true

[[analyzers]]
name = "go"
enabled = true

[[analyzers]]
name = "swift"
enabled = true

[[analyzers]]
name = "kotlin"
enabled = true
